version: "3"

services:

  cron:
    image: leo/docker-flow-cron:${TAG:-latest}
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT:-8080}:8080
    deploy:
      placement:
        constraints: [node.role == manager]
  
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://cron:8080/v1/docker-flow-cron/job/create
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://cron:8080/v1/docker-flow-cron/job/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  job:
    image: alpine:3.5
    depends_on:
      - swarm-listener
      - cron
    networks:
      - proxy
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - com.df.notify=true
        - com.df.name=cron_job
        - com.df.image=alpine
        - com.df.command=echo \"hello World\"
        - com.df.schedule=@every 30s
networks:
  proxy:
    external: true