version: '2'


services:

  unit:
    image: vfarcic/docker-flow-cron-test
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t ./... && go test --cover ./... -p=1 && go build -v -o docker-flow-cron"

  docs:
    image: cilerler/mkdocs
    volumes:
      - .:/docs
    command: bash -c "pip install pygments && pip install pymdown-extensions && mkdocs build"
